# Generated by Django 4.0.1 on 2022-06-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifyme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
